# Generated by Django 3.1.5 on 2021-01-06 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=50)),
                ('a', models.CharField(max_length=30)),
                ('b', models.CharField(max_length=30)),
                ('c', models.CharField(max_length=30)),
                ('d', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ans', models.CharField(max_length=30)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApi.createtest')),
            ],
        ),
    ]
